### PR TITLE
Make extension-setting gulp-version-agnostic

### PR DESCRIPTION
**Pull request by spencer-brown**
Fixes https://github.com/lazd/gulp-handlebars/issues/89.

---

This change can be tested by `link`ing this branch of `gulp-handlebars` in the [bug demonstration repo](https://github.com/spencer-brown/gulp-handlebars-bug-demo) I made.

### CODE REVIEW

**Comment by spencer-brown** [comment]
cc @lazd :D

**Comment by lazd** [comment]
This is awesome, you're awesome, and merged!

**Comment by spencer-brown** [comment]
thanks, @lazd !

**Comment by lazd** [comment]
@spencer-brown this seems to have introduced #91, can you look into it?

**Comment by spencer-brown** [comment]
@lazd sorry i couldn't help in time & glad it got figured out quickly!

**Pull request merged**
